package parser;

public enum BodyFlag {
	BODY_IS_FLAG_FUNCTION,
	BODY_IS_FLAG_STRUCT,
	BODY_IS_FLAG_CLASS,
	BODY_IS_FLAG_UNION,
	BODY_IS_FLAG_TRY_CATCH_STATEMENT,
	BODY_IS_FLAG_CATCH_STATEMENT,
	BODY_IS_FLAG_IF_STATEMENT,
	BODY_IS_FLAG_ELSE_STATEMENT,
	BODY_IS_FLAG_FOR_LOOP_STATEMENT,
	BODY_IS_FLAG_FOR_EACH_LOOP_STATEMENT,
	BODY_IS_FLAG_DO_WHILE_LOOP_STATEMENT,
	BODY_IS_FLAG_WHILE_LOOP_STATEMENT,
	BODY_IS_FLAG_SWITCH_STATEMENT,
	BODY_IS_FLAG_CASE_STATEMENT,
	BODY_IS_FLAG_DEFAULT_STATEMENT,
	BODY_IS_FLAG_SYMBOL,
	BODY_IS_FLAG_NAMESPACE
}
