package cleanCodeAnalyzer;

public enum CleanCodeAnalysisConcreteCategory {
	IDENTIFIER_ANALYSIS,
	ACCESS_SPECIFIER_ANALYSIS,
	HEIGHT_ANALYSIS,
	WIDTH_ANALYSIS,
	INDENTATION_ANALYSIS,
	STMT_ANALYSIS,
	METHOD_HEAD_ANALYSIS,
	COMMENT_ANALYSIS,
	FILE_SIZE_ANALYSIS,
	VERTICAL_DENSITY_ANALYSIS,
	ASSIGNMENT_ANALYSIS,
	FILE_HEAD_ANALYSIS,
	EXPRESSION_ANALYSIS,
	USAGE_ANALYSIS,
}
