package parserDatatypes;

public enum FunctionFlag {
	FUNCTION_NODE_FLAG_IS_NATIVE, // Native Funktionen erhalten diese Flag.
	FUNCTION_NODE_FLAG_IS_NATIVE_CONSTRUCTOR,
	FUNCTION_NODE_FLAG_IS_NATIVE_DESTRUCTOR,
	FUNCTION_NODE_FLAG_IS_NATIVE_OVERLOADED_OPERATOR
}
